### ISSUE TITLE
Games are pulled, but no data

### ISSUE THREAD

**Issue by MM131393** [llSourcell/ChatGPT_Sports_Betting_Bot#5]
I'm using Colab, and I'm able to load games occurring on the day of, but I get this series of text when I run !python3 main.py -A -odds=fanduel

Traceback (most recent call last):
  File "/content/main.py", line 106, in <module>
    main()
  File "/content/main.py", line 79, in main
    data, todays_games_uo, frame_ml, home_team_odds, away_team_odds = createTodaysGames(games, df, odds)
  File "/content/main.py", line 52, in createTodaysGames
    frame_ml = games_data_frame.drop(columns=['TEAM_ID', 'CFID', 'CFPARAMS', 'TEAM_NAME'])
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4906, in drop
    return super().drop(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 4214, in _drop_axis
    raise KeyError(f"{labels} not found in axis")
KeyError: "['TEAM_ID' 'CFID' 'CFPARAMS' 'TEAM_NAME'] not found in axis"

Anyidea of this issue?

**Comment by gwhnhs** [comment]
i'm having the same issue
